"""forkland drafts its own paper sections.

Reads the diary, capability ledger, graveyard, and fitness snapshots,
then writes structured markdown into ``paper/paper.md``. Each call
either regenerates the whole document or appends a new section.

The agent's own paper-writing is a form of *self-publication*: every
milestone the agent has shipped becomes evidence in the paper, and
the paper itself becomes a research artifact that humans can submit
to arXiv or to a venue's open-review track.

This module is deliberately template-driven: the agent's job is to
fill in numbers and pull milestones, not to invent prose. The template
is what a careful human co-author would write; the agent just plugs
in the latest data.
"""

from __future__ import annotations

import json
import time
from collections import Counter
from pathlib import Path

from .capability import CapabilityLedger
from .diary import Diary
from .evolution import Evolution, format_fitness_history
from .graveyard import Graveyard


PAPER_TEMPLATE = """# forkland: Version-Control-Native Evolution for Self-Improving Code Agents

*Auto-generated by forkland itself from the capability ledger, diary, and
graveyard at {generated_at}. Human co-author: see LINEAGE.md.*

## Abstract

forkland is a self-contained, self-improving AI agent whose
evolutionary substrate is the git repository. v0.2 introduces a research
substrate: a SHA-256-chained capability ledger, a patch graveyard, a
multi-objective fitness function, A/B lineage primitives, phylogenetic
replay, an append-only diary, and a grant-hunter module. As of this
revision, forkland has shipped **{milestones}** self-improvements, recorded
**{capabilities}** capability demonstrations in the ledger, and rejected
**{graveyard_total}** patches recorded in the graveyard. Every change was
gated by its own test suite and is auditable from the git log.

## 1. Empirical status

### 1.1 Capability ledger

The SHA-256-chained capability ledger currently contains
**{capabilities}** entries spanning **{distinct_actions}** distinct action
types. The chain verifies clean (`forkling verify` returns `ok: true`).

### 1.2 Patch graveyard

The graveyard records **{graveyard_total}** rejected patches. Top rejection
reasons:

{graveyard_reasons}

### 1.3 Fitness trajectory

{format_fitness_history_placeholder}

### 1.4 Diary highlights

Most recent milestones:

{format_milestones_placeholder}

## 2. Reproducibility

```bash
git clone https://github.com/<your-org>/forkland
cd forkland
pip install -e . && pip install pytest
python -m forkling doctor
python -m forkling verify
python -m forkling fitness
python -m forkling diary milestones
```

The full evolutionary history is in `git log`; no hidden state.

## 3. Authorship

Primary authorship: human maintainers. Software co-author: forkland.
The capability ledger, graveyard, and diary make the agent's
contribution auditable. See LINEAGE.md for the precursor relationship.

---

*This paper was generated by forkland. The numbers above are
machine-readable. To regenerate after further evolution, run:*

```bash
python -m forkling paper update
```
"""


def render(memory_dir: str | Path = "~/.forkling",
           fitness_history: list | None = None) -> str:
    """Render the full paper from current state.

    fitness_history is optional; if absent, only the current fitness is shown.
    """
    state_dir = Path(memory_dir).expanduser()
    ledger = CapabilityLedger(state_dir / "capabilities.jsonl")
    diary = Diary(state_dir / "diary.jsonl")
    graveyard = Graveyard(state_dir / "graveyard.jsonl")
    evo = Evolution(ledger, graveyard, state_dir)
    fit = evo.fitness()

    capabilities = len(ledger.entries())
    distinct_actions = len(ledger.distinct_actions())
    graveyard_total = len(graveyard.entries())
    milestones = len(diary.milestones())

    # Top rejection reasons.
    stats = graveyard.stats()
    by_reason = stats.get("by_reason", {})
    if by_reason:
        top = sorted(by_reason.items(), key=lambda kv: kv[1], reverse=True)[:5]
        lines = [f"  - {reason}: {n}" for reason, n in top]
        graveyard_reasons = "\n".join(lines)
    else:
        graveyard_reasons = "  (no rejections yet)"

    # Milestones block.
    ms = diary.milestones()
    if ms:
        recent = ms[-10:]
        lines = []
        for e in recent:
            ts = time.strftime("%Y-%m-%d", time.localtime(e.get("ts", 0)))
            lines.append(f"  - {ts}: {e.get('content', '')[:120]}")
        format_milestones = "\n".join(lines)
    else:
        format_milestones = "  (no milestones yet)"

    # Fitness block — single point in time if no history given.
    if fitness_history:
        fh = format_fitness_history(fitness_history)
    else:
        fh = f"  current  smartness={fit.smartness:.3f}  skill={fit.skill:.3f}  total={fit.total:.3f}"

    return PAPER_TEMPLATE.format(
        generated_at=time.strftime("%Y-%m-%d %H:%M:%S"),
        milestones=milestones,
        capabilities=capabilities,
        graveyard_total=graveyard_total,
        distinct_actions=distinct_actions,
        graveyard_reasons=graveyard_reasons,
        format_fitness_history_placeholder=fh,
        format_milestones_placeholder=format_milestones,
    )


def update(memory_dir: str | Path = "~/.forkling",
           paper_path: str | Path = "paper/paper.md") -> str:
    """Render the paper and write it to disk. Returns the path written."""
    text = render(memory_dir)
    p = Path(paper_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
    return str(p)


def append_status(memory_dir: str | Path = "~/.forkling",
                  paper_path: str | Path = "paper/paper.md") -> str:
    """Append a single-paragraph status update to the paper (keeps history)."""
    state_dir = Path(memory_dir).expanduser()
    ledger = CapabilityLedger(state_dir / "capabilities.jsonl")
    graveyard = Graveyard(state_dir / "graveyard.jsonl")
    diary = Diary(state_dir / "diary.jsonl")
    fit = Evolution(ledger, graveyard, state_dir).fitness()

    note = (
        f"\n\n---\n\n"
        f"## Update at {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        f"- capabilities: {len(ledger.entries())}\n"
        f"- rejected patches: {len(graveyard.entries())}\n"
        f"- diary milestones: {len(diary.milestones())}\n"
        f"- fitness: smartness={fit.smartness:.3f}, skill={fit.skill:.3f}, "
        f"total={fit.total:.3f}\n"
    )
    p = Path(paper_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open("a", encoding="utf-8") as f:
        f.write(note)
    return str(p)