"""forkling drafts its own paper sections.

Reads the diary, capability ledger, graveyard, and fitness snapshots,
then writes structured markdown into ``paper/paper.md``. Each call
either regenerates the whole document or appends a new section.

The agent's own paper-writing is a form of *self-publication*: every
milestone the agent has shipped becomes evidence in the paper, and
the paper itself becomes a research artifact that humans can submit
to arXiv or to a venue's open-review track.

This module is deliberately template-driven: the agent's job is to
fill in numbers and pull milestones, not to invent prose. The template
is what a careful human co-author would write; the agent just plugs
in the latest data.
"""

from __future__ import annotations

import json
import time
from collections import Counter
from pathlib import Path

from .capability import CapabilityLedger
from .diary import Diary
from .evolution import Evolution, format_fitness_history
from .graveyard import Graveyard


PAPER_TEMPLATE = """# Forkland Forkling: Version-Control-Native Evolution for "Self-Contained" and Self-Improving Code Agents

*Auto-generated by forkling itself from the capability ledger, diary, and
graveyard at {generated_at}. Human co-author: see LINEAGE.md.*

## Abstract

The Darwin Gödel Machine (DGM) is the current high-water mark for
self-improving AI agents: it edits its own source code at inference
time, scores the edits with a benchmark-derived fitness function, and
keeps the best. **forkling** takes a different bet. It treats the git
history of its own repository — not the agent's in-memory state — as
the evolutionary substrate. Every patch is `git commit`-able, every
selection event is a `pytest` run, every rollback is a `git checkout`,
every parallel experiment is a `git branch`. The four primitives of
a Darwinian process map onto four git operations that already exist
in every developer's toolchain. This makes the agent's full
evolutionary history **trivially auditable**, **trivially replayable**,
and **trivially sharable**, with no hidden in-memory lineage and no
special-purpose substrate to maintain. As of this revision, forkling
has shipped **{milestones}** self-improvements, recorded
**{capabilities}** capability demonstrations in the ledger, and
rejected **{graveyard_total}** patches recorded in the graveyard.
Every change was gated by its own test suite and is auditable from
the git log.

## 1. Empirical status

### 1.1 Capability ledger

The SHA-256-chained capability ledger currently contains
**{capabilities}** entries spanning **{distinct_actions}** distinct action
types. The chain verifies clean (`forkling verify` returns `ok: true`).

### 1.2 Patch graveyard

The graveyard records **{graveyard_total}** rejected patches. Top rejection
reasons:

{graveyard_reasons}

### 1.3 Fitness trajectory

{format_fitness_history_placeholder}

### 1.4 Diary highlights

Most recent milestones:

{format_milestones_placeholder}

### 1.5 Controlled experiments

Three pre-registered experiments have run on FORKLAND-BENCH-001
(10 one-line Python bug fixes, K=10 attempts per task per arm).
All three are **null** under their pre-registered tests:

| Experiment | Question | Primary result |
|---|---|---|
| exp001 (`paper/hypothesis.md`) | Does in-loop selection beat one-shot and random acceptance? | NULL |
| exp002 (`paper/hypothesis_v2.md`) | Same, with `qwen2.5-coder:3b` and a tighter prompt | NULL |
| exp003 (`paper/hypothesis_v3.md`) | Is selection a filter or an amplifier (in-loop I vs post-hoc P)? | NULL: pass@5 I=0.80 vs P=0.90, U=45, p=0.71 |

A post-hoc audit of the harness (`paper/exp003_results.md`, section
"Validity caveat") found that these nulls cannot be read as evidence
about selection. Two properties of the harness, not of the model,
decide the outcome: the pass@k endpoint counts any held-out pass
among the first k draws whether or not the arm selected it, so it is
blind to post-hoc re-ranking by construction; and the in-loop arms
always prompt with the original `buggy.py` while applying patches to
the evolved source, so after the first accepted patch most later
patches no longer apply (in-loop parse_ok falls from 0.9 at attempt 0
to about 0.3 afterwards). exp003's post-hoc re-ranker also sorted
candidates the wrong way and committed the worst one. The benchmark
is also near ceiling (arm N pass@5 = 0.90). A fixed harness
(`forkling/experiment2.py`, protocol 2) must pass a self-test with
scripted models before use. exp003b (`paper/hypothesis_v3b.md`) reruns
exp003 on it, and exp004 is re-registered in
`paper/hypothesis_v4r1.md` on a harder, calibrated benchmark.

## 2. Substrate thesis (vs DGM)

The git-as-substrate thesis sits at the intersection of three
literatures. We position forkling against each.

### 2.1 Darwin Gödel Machine and self-modifying agents

The **Darwin Gödel Machine** (DGM) is the nearest published neighbor.
DGM edits the agent's own Python source at inference time, evaluates
candidate edits against a benchmark, and keeps the best. Forkland
differs on three axes:

| Axis | DGM | forkling |
|---|---|---|
| Substrate | in-memory source edits | git history (the working tree) |
| Selection | benchmark score | `pytest -q` (fitness gate on the actual code) |
| Auditability | requires post-hoc lineage reconstruction | `git log` *is* the lineage |
| Parallelism | single agent, in-memory tree | `git branch` per experiment |
| Replay | must reconstruct the edit DAG | `git checkout <sha>` + run |

The distinction matters because selection in forkling is **the
agent's own test suite**, not a benchmark. The agent has direct
incentive to make its own tests pass — and direct disincentive to
"game" the benchmark. That closes a known DGM failure mode where
edits that improve the score but degrade general capability persist
in the lineage. In forkling, such an edit would fail the agent's own
regression tests and be rolled back.

### 2.2 Genetic programming and evolutionary computation

Git-as-substrate connects to the **genetic programming** tradition
[Koza, 1992]: the genotype is the source code, the fitness function
is task success, the variation operator is mutation/crossover, and
selection is survival-of-the-fittest. Forkland's variation operator
is **unique-match patch** (`old` → `new`), which is a constrained
mutation; the **multi-objective fitness** in `forkling/evolution.py`
is a hand-crafted combination of capability-ledger coverage,
graveyard penalty, and Shannon-entropy file diversity.

Where classical GP tracks lineages in bespoke data structures, forkling's
lineage is **the git log**. We get phylogenetic replay,
ancestor-of comparison, and diff-replay for free.

### 2.3 Self-play RL on agent scaffolding

A growing family of work — **AlphaEvolve** [DeepMind, 2025],
**FunSearch** [Romera-Paredes et al., 2024], **ADAS** [Hu et al.,
2024] — evolves agent scaffolding using LLMs as variation operators
and benchmark scores as selection. Forkland shares the variation
story (LLM proposes an edit) but differs on selection: rather than
scoring against an external benchmark, it scores against its own
running test suite. This makes the agent's evolution
**task-relative** (good at being forkling) rather than
**benchmark-relative** (good at SWE-bench).

## 3. Reproducibility

```bash
git clone https://github.com/<your-org>/forkling
cd forkling
pip install -e . && pip install pytest
python -m forkling doctor
python -m forkling verify
python -m forkling fitness
python -m forkling diary milestones
```

The full evolutionary history is in `git log`; no hidden state. Every
stage of the 365-day cycle ships a frozen paper at
`paper/papers/<stage>.md`; the rolling draft is regenerated by
`forkling paper update`; the year-1 dataset is exported by
`forkling export-dataset`.

## 4. Authorship

Primary authorship: human maintainers. Software co-author: forkling.
The capability ledger, graveyard, and diary make the agent's
contribution auditable. See LINEAGE.md for the precursor relationship.

---

*This paper was generated by forkling. The numbers above are
machine-readable. To regenerate after further evolution, run:*

```bash
python -m forkling paper update
```
"""


def render(memory_dir: str | Path = "~/.forkling",
           fitness_history: list | None = None) -> str:
    """Render the full paper from current state.

    fitness_history is optional; if absent, only the current fitness is shown.
    """
    state_dir = Path(memory_dir).expanduser()
    ledger = CapabilityLedger(state_dir / "capabilities.jsonl")
    diary = Diary(state_dir / "diary.jsonl")
    graveyard = Graveyard(state_dir / "graveyard.jsonl")
    evo = Evolution(ledger, graveyard, state_dir)
    fit = evo.fitness()

    capabilities = len(ledger.entries())
    distinct_actions = len(ledger.distinct_actions())
    graveyard_total = len(graveyard.entries())
    milestones = len(diary.milestones())

    # Top rejection reasons.
    stats = graveyard.stats()
    by_reason = stats.get("by_reason", {})
    if by_reason:
        top = sorted(by_reason.items(), key=lambda kv: kv[1], reverse=True)[:5]
        lines = [f"  - {reason}: {n}" for reason, n in top]
        graveyard_reasons = "\n".join(lines)
    else:
        graveyard_reasons = "  (no rejections yet)"

    # Milestones block.
    ms = diary.milestones()
    if ms:
        recent = ms[-10:]
        lines = []
        for e in recent:
            ts = time.strftime("%Y-%m-%d", time.localtime(e.get("ts", 0)))
            lines.append(f"  - {ts}: {e.get('content', '')[:120]}")
        format_milestones = "\n".join(lines)
    else:
        format_milestones = "  (no milestones yet)"

    # Fitness block — single point in time if no history given.
    if fitness_history:
        fh = format_fitness_history(fitness_history)
    else:
        fh = f"  current  smartness={fit.smartness:.3f}  skill={fit.skill:.3f}  total={fit.total:.3f}"

    return PAPER_TEMPLATE.format(
        generated_at=time.strftime("%Y-%m-%d %H:%M:%S"),
        milestones=milestones,
        capabilities=capabilities,
        graveyard_total=graveyard_total,
        distinct_actions=distinct_actions,
        graveyard_reasons=graveyard_reasons,
        format_fitness_history_placeholder=fh,
        format_milestones_placeholder=format_milestones,
    )


def update(memory_dir: str | Path = "~/.forkling",
           paper_path: str | Path = "paper/paper.md") -> str:
    """Render the paper and write it to disk. Returns the path written."""
    text = render(memory_dir)
    p = Path(paper_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
    return str(p)


def append_status(memory_dir: str | Path = "~/.forkling",
                  paper_path: str | Path = "paper/paper.md") -> str:
    """Append a single-paragraph status update to the paper (keeps history)."""
    state_dir = Path(memory_dir).expanduser()
    ledger = CapabilityLedger(state_dir / "capabilities.jsonl")
    graveyard = Graveyard(state_dir / "graveyard.jsonl")
    diary = Diary(state_dir / "diary.jsonl")
    fit = Evolution(ledger, graveyard, state_dir).fitness()

    note = (
        f"\n\n---\n\n"
        f"## Update at {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        f"- capabilities: {len(ledger.entries())}\n"
        f"- rejected patches: {len(graveyard.entries())}\n"
        f"- diary milestones: {len(diary.milestones())}\n"
        f"- fitness: smartness={fit.smartness:.3f}, skill={fit.skill:.3f}, "
        f"total={fit.total:.3f}\n"
    )
    p = Path(paper_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open("a", encoding="utf-8") as f:
        f.write(note)
    return str(p)