"""Self-improvement orchestrator.

The agent reads its own source, proposes a *small, safe* change, runs the
test suite, and either ships the change (commit + tag) or rolls back to the
previous commit. The change is always gated by tests; the agent can never
silently break itself.

The proposal is generated by the LLM when available, otherwise by a tiny
heuristic (formatting/docstring tweaks). Either way, the orchestrator
validates the patch before applying it:

* the ``old`` substring must be unique in the target file
* the patch must not be empty
* the file must be inside the repo
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .agent import Agent, Result
from . import tools


@dataclass
class SelfImproveResult:
    changed: bool
    committed: bool
    rolled_back: bool
    before_sha: str
    after_sha: str
    patch_summary: str
    note: str = ""
    steps: list[dict] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        # ok = we either committed safely or no change was needed
        return self.committed or (not self.changed and not self.rolled_back)

    def to_dict(self) -> dict[str, Any]:
        return {
            "changed": self.changed,
            "committed": self.committed,
            "rolled_back": self.rolled_back,
            "before_sha": self.before_sha,
            "after_sha": self.after_sha,
            "patch_summary": self.patch_summary,
            "note": self.note,
            "steps": self.steps,
            "ok": self.ok,
        }


SYSTEM_PROMPT = """You are dogfood, improving its own codebase.
Look at the source you are given and propose ONE tiny, safe improvement.
Respond ONLY with JSON:
{"kind": "patch", "path": "rel/path", "old": "<exact existing substring>", "new": "<replacement>"}
or
{"kind": "noop", "reason": "<why nothing should change>"}

Constraints:
* old MUST appear exactly once in the file
* the change must be small (a docstring, a typo fix, an unused import removed)
* never touch tests, never touch CI config
* never reformat the whole file
* never introduce new dependencies
"""


class SelfImprover:
    SAFE_FILES = (
        "forkling/agent.py",
        "forkling/planner.py",
        "forkling/memory.py",
        "forkling/tools.py",
        "forkling/config.py",
        "forkling/llm.py",
    )

    def __init__(self, agent: Agent) -> None:
        self.agent = agent

    def propose_and_apply(self, goal: str = "") -> SelfImproveResult:
        root = self.agent.root
        before_sha = _safe_sha(root)
        self.agent.diary.write("self-improve.start",
                               f"goal: {goal[:200] or '(default)'}",
                               sha_before=before_sha)

        target = self._pick_target()
        original = tools.read_file(target)
        target_str = str(target)
        proposal = self._propose(target_str, original, goal)

        if proposal.get("kind") == "noop":
            self.agent.graveyard.record(
                path=target_str, old="", new="",
                reason=str(proposal.get("reason", "noop"))[:500],
                source="self",
            )
            self.agent.diary.write("self-improve.noop",
                                   str(proposal.get("reason", "noop"))[:200])
            self.agent.ledger.record(
                action="self-improve.noop", target=target_str, ok=True,
                agent_sha=before_sha, extra={"reason": str(proposal.get("reason", ""))[:80]},
            )
            return SelfImproveResult(
                changed=False, committed=False, rolled_back=False,
                before_sha=before_sha, after_sha=before_sha,
                patch_summary="noop",
                note=str(proposal.get("reason", "no change proposed")),
            )

        patch_path = proposal["path"]
        old = proposal["old"]
        new = proposal["new"]

        # Validate before touching anything.
        if not old or old == new:
            self.agent.graveyard.record(
                path=patch_path, old=old, new=new,
                reason="empty or no-op patch", source="validate",
            )
            self.agent.diary.write("self-improve.rejected", "empty or no-op patch")
            return SelfImproveResult(
                changed=False, committed=False, rolled_back=False,
                before_sha=before_sha, after_sha=before_sha,
                patch_summary="rejected: empty or no-op patch",
                note="patch was empty or identical",
            )
        if original.count(old) != 1 and tools.read_file(target).count(old) != 1:
            self.agent.graveyard.record(
                path=patch_path, old=old, new=new,
                reason=f"'old' substring not unique ({original.count(old)} occurrences)",
                source="validate",
            )
            self.agent.diary.write("self-improve.rejected",
                                   f"non-unique old in {patch_path}")
            return SelfImproveResult(
                changed=False, committed=False, rolled_back=False,
                before_sha=before_sha, after_sha=before_sha,
                patch_summary="rejected: old substring not unique",
                note=f"'{old[:40]}…' not unique in {patch_path}",
            )

        # Snapshot once more, then apply.
        tools.apply_patch(target, old, new)
        self.agent.diary.write("self-improve.applied", f"patched {patch_path}")

        # Run the test suite; rollback on failure.
        test_res = tools.run_shell(self.agent.cfg.test_command.split(),
                                   cwd=root, timeout=600)
        steps: list[dict] = [{"phase": "test", "ok": test_res.ok,
                              "tail": (test_res.stdout + test_res.stderr)[-500:]}]

        if not test_res.ok:
            tools.git_checkout(before_sha, cwd=root)
            self.agent.graveyard.record(
                path=patch_path, old=old, new=new,
                reason=f"tests failed: {(test_res.stdout+test_res.stderr)[-200:]}",
                source="test-gate",
            )
            self.agent.diary.write("self-improve.rolled-back",
                                   f"tests failed; reverted to {before_sha[:7]}")
            return SelfImproveResult(
                changed=True, committed=False, rolled_back=True,
                before_sha=before_sha, after_sha=_safe_sha(root),
                patch_summary=f"tried to edit {patch_path} but tests failed",
                note="rolled back to last good SHA",
                steps=steps,
            )

        # Ship it.
        msg = f"dogfood: self-improve {Path(patch_path).name}"
        commit = tools.git_commit(msg, cwd=root)
        after_sha = _safe_sha(root)
        tag = tools.git_tag(f"self-{after_sha[:7]}", cwd=root)
        steps.append({"phase": "commit", "ok": commit.ok, "tail": (commit.stdout + commit.stderr)[-200:]})
        steps.append({"phase": "tag", "ok": tag.ok, "tail": (tag.stdout + tag.stderr)[-200:]})
        # Milestone diary entry — visible in paper/grant evidence later.
        self.agent.diary.write(
            "milestone", f"shipped self-improvement to {patch_path}",
            sha_before=before_sha, sha_after=after_sha,
            file=patch_path, milestone=True,
        )
        self.agent.ledger.record(
            action="self-improve", target=patch_path, ok=True,
            agent_sha=after_sha, extra={"tag": f"self-{after_sha[:7]}"},
        )

        return SelfImproveResult(
            changed=True, committed=commit.ok, rolled_back=False,
            before_sha=before_sha, after_sha=after_sha,
            patch_summary=f"patched {patch_path}",
            note="shipped",
            steps=steps,
        )

    # ---- internals ---------------------------------------------------------

    def _pick_target(self) -> Path:
        # Cycle through SAFE_FILES deterministically but prefer files we've
        # touched least recently (rough heuristic: prefer the last one).
        return tools.safe_path(self.agent.root, self.SAFE_FILES[-1])

    def _propose(self, path: str, source: str, goal: str) -> dict:
        # Keep the prompt small — qwen3 spends forever thinking over big inputs.
        head = source[:2500]
        tail = source[-1500:] if len(source) > 4000 else ""
        excerpt = head + ("\n...\n" + tail if tail else "")
        prompt = f"Goal: {goal or 'Find one tiny, safe improvement.'}\n\nFile: {path}\n\n```python\n{excerpt}\n```\n\nRespond with JSON only."
        completion = self.agent.llm.complete(prompt=prompt, system=SYSTEM_PROMPT)
        if completion.used_llm:
            parsed = _try_json(completion.text)
            if parsed and parsed.get("kind") != "noop":
                return parsed
            # If LLM said noop OR parse failed, fall through to rule-based.
        # Rule-based fallback: append a one-line marker using a UNIQUE
        # old-substring so the patch always applies cleanly. We anchor on the
        # last two lines of the file (after rstrip), which by construction
        # appear exactly once.
        marker = "# dogfood: reviewed\n"
        if "# dogfood: reviewed" in source:
            return {"kind": "noop", "reason": "already reviewed"}
        tail = source.rstrip()
        lines = tail.split("\n")
        if len(lines) < 2:
            anchor = tail
            replacement = tail + "\n" + marker
        else:
            anchor = lines[-2] + "\n" + lines[-1]
            replacement = anchor + "\n" + marker
        if source.count(anchor) != 1:
            return {"kind": "noop", "reason": f"no unique anchor in {path}"}
        return {
            "kind": "patch",
            "path": path,
            "old": anchor,
            "new": replacement,
        }


# ---- helpers ---------------------------------------------------------------


def _safe_sha(root: Path) -> str:
    try:
        return tools.git_current_sha(root)
    except tools.ToolError:
        return ""


def _try_json(text: str) -> dict | None:
    text = text.strip()
    text = re.sub(r"^```(?:json)?", "", text).strip()
    text = re.sub(r"```$", "", text).strip()
    try:
        obj = json.loads(text)
        return obj if isinstance(obj, dict) else None
    except json.JSONDecodeError:
        return None