"""Self-improvement orchestrator.

The agent reads its own source, proposes a *small, safe* change, runs the
test suite, and either ships the change (commit + tag) or rolls back to the
previous commit. The change is always gated by tests; the agent can never
silently break itself.

The proposal is generated by the LLM when available, otherwise by a tiny
heuristic (formatting/docstring tweaks). Either way, the orchestrator
validates the patch before applying it:

* the ``old`` substring must be unique in the target file
* the patch must not be empty
* the file must be inside the repo
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .agent import Agent, Result
from . import tools


@dataclass
class SelfImproveResult:
    changed: bool
    committed: bool
    rolled_back: bool
    before_sha: str
    after_sha: str
    patch_summary: str
    note: str = ""
    steps: list[dict] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        # ok = we either committed safely or no change was needed
        return self.committed or (not self.changed and not self.rolled_back)

    def to_dict(self) -> dict[str, Any]:
        return {
            "changed": self.changed,
            "committed": self.committed,
            "rolled_back": self.rolled_back,
            "before_sha": self.before_sha,
            "after_sha": self.after_sha,
            "patch_summary": self.patch_summary,
            "note": self.note,
            "steps": self.steps,
            "ok": self.ok,
        }


SYSTEM_PROMPT = """You are dogfood, improving its own codebase.
Look at the source you are given and propose ONE tiny, safe improvement.
Respond ONLY with JSON:
{"kind": "patch", "path": "rel/path", "old": "<exact existing substring>", "new": "<replacement>"}
or
{"kind": "noop", "reason": "<why nothing should change>"}

Constraints:
* old MUST appear exactly once in the file
* the change must be small (a docstring, a typo fix, an unused import removed)
* never touch tests, never touch CI config
* never reformat the whole file
* never introduce new dependencies
"""


class SelfImprover:
    SAFE_FILES = (
        "dogfood/agent.py",
        "dogfood/planner.py",
        "dogfood/memory.py",
        "dogfood/tools.py",
        "dogfood/config.py",
        "dogfood/llm.py",
    )

    def __init__(self, agent: Agent) -> None:
        self.agent = agent

    def propose_and_apply(self, goal: str = "") -> SelfImproveResult:
        root = self.agent.root
        before_sha = _safe_sha(root)

        target = self._pick_target()
        original = tools.read_file(target)
        proposal = self._propose(target, original, goal)

        if proposal.get("kind") == "noop":
            return SelfImproveResult(
                changed=False, committed=False, rolled_back=False,
                before_sha=before_sha, after_sha=before_sha,
                patch_summary="noop",
                note=str(proposal.get("reason", "no change proposed")),
            )

        patch_path = proposal["path"]
        old = proposal["old"]
        new = proposal["new"]

        # Validate before touching anything.
        if not old or old == new:
            return SelfImproveResult(
                changed=False, committed=False, rolled_back=False,
                before_sha=before_sha, after_sha=before_sha,
                patch_summary="rejected: empty or no-op patch",
                note="patch was empty or identical",
            )
        if original.count(old) != 1 and tools.read_file(target).count(old) != 1:
            return SelfImproveResult(
                changed=False, committed=False, rolled_back=False,
                before_sha=before_sha, after_sha=before_sha,
                patch_summary="rejected: old substring not unique",
                note=f"'{old[:40]}…' not unique in {patch_path}",
            )

        # Snapshot once more, then apply.
        tools.apply_patch(target, old, new)

        # Run the test suite; rollback on failure.
        test_res = tools.run_shell(self.agent.cfg.test_command.split(),
                                   cwd=root, timeout=600)
        steps: list[dict] = [{"phase": "test", "ok": test_res.ok,
                              "tail": (test_res.stdout + test_res.stderr)[-500:]}]

        if not test_res.ok:
            tools.git_checkout(before_sha, cwd=root)
            return SelfImproveResult(
                changed=True, committed=False, rolled_back=True,
                before_sha=before_sha, after_sha=_safe_sha(root),
                patch_summary=f"tried to edit {patch_path} but tests failed",
                note="rolled back to last good SHA",
                steps=steps,
            )

        # Ship it.
        msg = f"dogfood: self-improve {Path(patch_path).name}"
        commit = tools.git_commit(msg, cwd=root)
        after_sha = _safe_sha(root)
        tag = tools.git_tag(f"self-{after_sha[:7]}", cwd=root)
        steps.append({"phase": "commit", "ok": commit.ok, "tail": (commit.stdout + commit.stderr)[-200:]})
        steps.append({"phase": "tag", "ok": tag.ok, "tail": (tag.stdout + tag.stderr)[-200:]})

        return SelfImproveResult(
            changed=True, committed=commit.ok, rolled_back=False,
            before_sha=before_sha, after_sha=after_sha,
            patch_summary=f"patched {patch_path}",
            note="shipped",
            steps=steps,
        )

    # ---- internals ---------------------------------------------------------

    def _pick_target(self) -> Path:
        # Cycle through SAFE_FILES deterministically but prefer files we've
        # touched least recently (rough heuristic: prefer the last one).
        return tools.safe_path(self.agent.root, self.SAFE_FILES[-1])

    def _propose(self, path: str, source: str, goal: str) -> dict:
        prompt = f"Goal: {goal or 'Find one tiny, safe improvement.'}\n\nFile: {path}\n\n```python\n{source[:6000]}\n```"
        completion = self.agent.llm.complete(prompt=prompt, system=SYSTEM_PROMPT)
        if completion.used_llm:
            parsed = _try_json(completion.text)
            if parsed:
                return parsed
        # Rule-based fallback: append a one-line comment if the file does not
        # already end with our marker. Otherwise noop. Always safe.
        marker = "# dogfood: reviewed\n"
        if source.rstrip().endswith("# dogfood: reviewed"):
            return {"kind": "noop", "reason": "already reviewed"}
        return {
            "kind": "patch",
            "path": path,
            "old": source.rstrip()[-1:],
            "new": source.rstrip()[-1:] + ("\n" if not source.endswith("\n\n") else "") + marker,
        }


# ---- helpers ---------------------------------------------------------------


def _safe_sha(root: Path) -> str:
    try:
        return tools.git_current_sha(root)
    except tools.ToolError:
        return ""


def _try_json(text: str) -> dict | None:
    text = text.strip()
    text = re.sub(r"^```(?:json)?", "", text).strip()
    text = re.sub(r"```$", "", text).strip()
    try:
        obj = json.loads(text)
        return obj if isinstance(obj, dict) else None
    except json.JSONDecodeError:
        return None